export const GET_CODEDAO_ARTICLE_LOADING = "GET_CODEDAO_ARTICLE_LOADING";
export const GET_CODEDAO_ARTICLE_SUCCESS = "GET_CODEDAO_ARTICLE_SUCCESS";
export const GET_CODEDAO_ARTICLE_FAILURE = "GET_CODEDAO_ARTICLE_FAILURE";
