version: "3"
services:
    web:
        build:
            context: .
            dockerfile: ./dev.Dockerfile
        expose:
            - 3001
        ports:
            - 3001:3001
        image: fptu-app-dev
        container_name: fptu-app-dev
        volumes:
            - ./public:/root/src/app/public
            - ./src:/root/src/app/src
        tty: true
