export const GET_HOME_ARTICLE_LOADING = "GET_HOME_ARTICLE_LOADING";
export const GET_HOME_ARTICLE_SUCCESS = "GET_HOME_ARTICLE_SUCCESS";
export const GET_HOME_ARTICLE_FAILURE = "GET_HOME_ARTICLE_FAILURE";
