export const GET_MEDIUM_ARTICLE_LOADING = "GET_MEDIUM_ARTICLE_LOADING";
export const GET_MEDIUM_ARTICLE_SUCCESS = "GET_MEDIUM_ARTICLE_SUCCESS";
export const GET_MEDIUM_ARTICLE_FAILURE = "GET_MEDIUM_ARTICLE_FAILURE";
export const LOAD_MORE_ARTICLE = "LOAD_MORE_ARTICLE";
