export const SE = [
    {
        id         : 1,
        subjectCode: "PRO001",
        subjectName: "Programming with Alice",
        termNo     : 0,
    },
    {
        id         : 2,
        subjectCode: "VOV114",
        subjectName: "Vovinam 1_2",
        termNo     : 0,
    },
    {
        id         : 3,
        subjectCode: "VOV124",
        subjectName: "Vovinam 3_4",
        termNo     : 0,
    },
    {
        id         : 4,
        subjectCode: "VOV134",
        subjectName: "Vovinam 5_6",
        termNo     : 0,
    },
    {
        id         : 5,
        subjectCode: "MAE101",
        subjectName: "Mathematics for Engineering",
        termNo     : 1,
    },
    {
        id         : 6,
        subjectCode: "CEA201",
        subjectName: "Computer Organization and Architecture",
        termNo     : 1,
    },
    {
        id         : 7,
        subjectCode: "CSI101",
        subjectName: "Connecting to Computer Science",
        termNo     : 1,
    },
    {
        id         : 8,
        subjectCode: "PRF192",
        subjectName: "Programming Fundamentals",
        termNo     : 1,
    },
    {
        id         : 9,
        subjectCode: "SSG101",
        subjectName: "Working in Group Skills",
        termNo     : 1,
    },
    {
        id         : 10,
        subjectCode: "DBI202",
        subjectName: "Introduction to Databases",
        termNo     : 2,
    },
    {
        id         : 11,
        subjectCode: "PRO201",
        subjectName: "Front-end Web Development",
        termNo     : 2,
    },
    {
        id         : 12,
        subjectCode: "PRO192",
        subjectName: "Object-Oriented Programming",
        termNo     : 2,
    },
    {
        id         : 13,
        subjectCode: "MAD101",
        subjectName: "Discrete mathematics",
        termNo     : 2,
    },
    {
        id         : 14,
        subjectCode: "LAB101",
        subjectName: "C Lab",
        termNo     : 2,
    },
    {
        id         : 15,
        subjectCode: "PRJ311",
        subjectName: "Desktop Java Applications",
        termNo     : 3,
    },
    {
        id         : 16,
        subjectCode: "LAB211",
        subjectName: "OOP with Java Lab",
        termNo     : 3,
    },
    {
        id         : 17,
        subjectCode: "CSD201",
        subjectName: "Data Structures and Algorithms",
        termNo     : 3,
    },
    {
        id         : 18,
        subjectCode: "OSG202",
        subjectName: "Operating Systems",
        termNo     : 3,
    },
    {
        id         : 19,
        subjectCode: "JPD111",
        subjectName: "Japanese 1",
        termNo     : 3,
    },
    {
        id         : 20,
        subjectCode: "SWE102",
        subjectName: "Introduction to Software Engineering",
        termNo     : 4,
    },
    {
        id         : 21,
        subjectCode: "JPD121",
        subjectName: "Japanese Elementary 2",
        termNo     : 4,
    },
    {
        id         : 22,
        subjectCode: "PRJ321",
        subjectName: "Web-Based Java Applications",
        termNo     : 4,
    },
    {
        id         : 23,
        subjectCode: "NWC202",
        subjectName: "Computer Networking",
        termNo     : 4,
    },
    {
        id         : 24,
        subjectCode: "LAB221",
        subjectName: "Desktop Java Lab",
        termNo     : 4,
    },
    {
        id         : 25,
        subjectCode: "JPD131",
        subjectName: "Japanese Elementary 3",
        termNo     : 5,
    },
    {
        id         : 26,
        subjectCode: "LAB231",
        subjectName: "Web Java Lab",
        termNo     : 5,
    },
    {
        id         : 27,
        subjectCode: "SWR301",
        subjectName: "Software Requirements",
        termNo     : 5,
    },
    {
        id         : 28,
        subjectCode: "SWQ391",
        subjectName: "Software Quality Assurance and Testing",
        termNo     : 5,
    },
    {
        id         : 29,
        subjectCode: "PRN292",
        subjectName: ".NET and C#",
        termNo     : 5,
    },
    {
        id         : 30,
        subjectCode: "OJS201",
        subjectName: "On the job training1",
        termNo     : 6,
    },
    {
        id         : 31,
        subjectCode: "SYB301",
        subjectName: "Start Your Business",
        termNo     : 6,
    },
    {
        id         : 32,
        subjectCode: "SWD391",
        subjectName: "Software Architecture and Design",
        termNo     : 7,
    },
    {
        id         : 33,
        subjectCode: "HCI201",
        subjectName: "Human-Computer Interaction",
        termNo     : 7,
    },
    {
        id         : 34,
        subjectCode: "PRM391",
        subjectName: "Mobile Programming",
        termNo     : 7,
    },
    {
        id         : 35,
        subjectCode: "ACC101",
        subjectName: "Principles of Accounting",
        termNo     : 7,
    },
    {
        id         : 36,
        subjectCode: "ISC301",
        subjectName: "e-Commerce",
        termNo     : 7,
    },
    {
        id         : 37,
        subjectCode: "PRX301",
        subjectName: "Web Development (XML)",
        termNo     : 8,
    },
    {
        id         : 38,
        subjectCode: "MAS291",
        subjectName: "Statistics and Probability",
        termNo     : 8,
    },
    {
        id         : 39,
        subjectCode: "DBW301",
        subjectName: "Data warehouse",
        termNo     : 8,
    },
    {
        id         : 40,
        subjectCode: "MLN101",
        subjectName: "Principles of Marxism - Leninism",
        termNo     : 8,
    },
    {
        id         : 41,
        subjectCode: "SWM301",
        subjectName: "Software project management",
        termNo     : 8,
    },
    {
        id         : 42,
        subjectCode: "HCM201",
        subjectName: "Ho Chi Minh Ideology",
        termNo     : 9,
    },
    {
        id         : 43,
        subjectCode: "VNR201",
        subjectName: "Revolutionary line of CPV",
        termNo     : 9,
    },
    {
        id         : 44,
        subjectCode: "PRC391",
        subjectName: "Cloud Computing",
        termNo     : 9,
    },
    {
        id         : 45,
        subjectCode: "SWP490",
        subjectName: "Capstone Project",
        termNo     : 9,
    },
    {
        id         : 46,
        subjectCode: "SSC102",
        subjectName: "Business Communication",
        termNo     : 9,
    },
    {
        id         : 47,
        subjectCode: "ITE302",
        subjectName: "Ethics in Information technology",
        termNo     : 9,
    },
];
